on: 
  pull_request:
    branches: [ main, dev ]

jobs: 
  build: 
    runs-on: ubuntu-latest
    name: Build and test
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup latest .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/
      
      - name: Build
        run: dotnet build --no-restore ./src/
      
      - name: Test
        run: dotnet test ./Tests/ --no-build --verbosity normal